# Spam Email Detection

In [1]:
import re
import pandas as pd
import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

In [2]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

# Dataset

In [3]:
df = pd.read_csv("spam.csv")
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

# Preprocessing

In [ ]:
# Lowercasing
def to_lowercase(text):
    return text.lower()

# Regular expression to remove HTML tags
def remove_html_tags(text):
    return re.sub(r'<.*?>', '', text)

# Regular expression to remove punctuation and numbers
def remove_punctuation_numbers(text):
    return re.sub(r'[^a-zA-Z\s]', '', text)

# Stop word removal
stop_words = set(stopwords.words('english'))
def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

# Tokenization
def tokenize_text(text):
    return word_tokenize(text)

# Stemming
stemmer = PorterStemmer()
def stem_tokens(tokens):
    return [stemmer.stem(word) for word in tokens]

# Lemmatization
lemmatizer = WordNetLemmatizer()
def lemmatize_tokens(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

# Full preprocessing pipeline
def preprocess_text(text):
    text = to_lowercase(text)
    text = remove_html_tags(text)
    text = remove_punctuation_numbers(text)
    
    tokens = tokenize_text(text)
    tokens = remove_stopwords(tokens)
    tokens = lemmatize_tokens(tokens)   # preferred over stemming
    
    return " ".join(tokens)

In [5]:
df['clean_Message'] = df['Message'].apply(preprocess_text)
df.head()

,Category,Message,clean_Message
0,ham,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,ham,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts st ...
3,ham,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,ham,"Nah I don't think he goes to usf, he lives aro...",nah dont think go usf life around though

In [8]:
# Before and after preprocessing
print("ORIGINAL TEXT:\n")
print(df['Message'][0])


print("\nPREPROCESSED TEXT:\n")
print(df['clean_Message'][0])

ORIGINAL TEXT:

Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...

PREPROCESSED TEXT:

go jurong point crazy available bugis n great world la e buffet cine got amore wat